#pragma once

#if defined(GREENFLAME_ENABLE_SUPERLUMINAL) && GREENFLAME_ENABLE_SUPERLUMINAL
#include <Superluminal/PerformanceAPI.h>

#define GREENFLAME_PROFILE_SCOPE(scope_name) PERFORMANCEAPI_INSTRUMENT(scope_name)
#define GREENFLAME_PROFILE_FUNCTION() PERFORMANCEAPI_INSTRUMENT_FUNCTION()
#else
#define GREENFLAME_PROFILE_SCOPE(scope_name)
#define GREENFLAME_PROFILE_FUNCTION()
#endif
